<?xml version="1.0" encoding="utf-8"?><Database Name="orderdatabase" Class="orderdatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WILL-EC4;Initial Catalog=orderdatabase;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="orderdatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="categoryid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="catdescription" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="category_restaurant" Member="restaurants" ThisKey="categoryid" OtherKey="categoryid" Type="restaurant" />
    </Type>
  </Table>
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="custemail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="custusername" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="custquestion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="custanswer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="custtelno" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="custname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="custaddress1" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="custaddress2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="custaddress3" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="custpostode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="custcomment" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="custupdatedate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="customerid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="customer_order" Member="orders" ThisKey="customerid" OtherKey="customerid" Type="order" />
    </Type>
  </Table>
  <Table Name="dbo.menu" Member="menus">
    <Type Name="menu">
      <Column Name="menuid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="restaurantid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="menutype" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="menustartdate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="menuexpirydate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="menucomment" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="menuupdatedate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="menu_menuitem" Member="menuitems" ThisKey="menuid" OtherKey="menuid" Type="menuitem" />
      <Association Name="restaurant_menu" Member="restaurant" ThisKey="restaurantid" OtherKey="restaurantid" Type="restaurant" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.menuitem" Member="menuitems">
    <Type Name="menuitem">
      <Column Name="menuitemid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="menuid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="itemname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="itemdescription" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="itemimage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="itemprice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="itempreptime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="itemcomment" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="itemupdatedate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="menuitem_orderline" Member="orderlines" ThisKey="menuitemid" OtherKey="menuitemid" Type="orderline" />
      <Association Name="menu_menuitem" Member="menu" ThisKey="menuid" OtherKey="menuid" Type="menu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[order]" Member="orders">
    <Type Name="order">
      <Column Name="customerid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="orderdate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="orderduedate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="orderstatus" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ordertotal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ordertrackingid" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="orderdeliverytime" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="ordercollectdeliver" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ordercomment" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="orderid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="order_orderline" Member="orderlines" ThisKey="orderid" OtherKey="orderid" Type="orderline" />
      <Association Name="customer_order" Member="customer" ThisKey="customerid" OtherKey="customerid" Type="customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.orderline" Member="orderlines">
    <Type Name="orderline">
      <Column Name="orderid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="orderlineno" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="menuitemid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="linequantity" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="linestatus" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="lineprice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="linepreptime" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="linecomment" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="menuitem_orderline" Member="menuitem" ThisKey="menuitemid" OtherKey="menuitemid" Type="menuitem" IsForeignKey="true" />
      <Association Name="order_orderline" Member="order" ThisKey="orderid" OtherKey="orderid" Type="order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.restaurant" Member="restaurants">
    <Type Name="restaurant">
      <Column Name="restaurantid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="categoryid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="restname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="restaddress1" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="restaddress2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="restaddress3" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="restpostcode" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="restdescription" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="resttelno" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="restemail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="restimage" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="restcomment" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="restupdatedate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="restaurant_menu" Member="menus" ThisKey="restaurantid" OtherKey="restaurantid" Type="menu" />
      <Association Name="category_restaurant" Member="category" ThisKey="categoryid" OtherKey="categoryid" Type="category" IsForeignKey="true" />
    </Type>
  </Table>
</Database>